### ISSUE TITLE
Error with 2 Whisperers

### ISSUE THREAD

**Issue by simons-plugins** [ChristopheG666/homebridge-netro-whisperer#1]
Hi,  

Very excited to find this plugin, but I get the following error when trying to use it for 2 Whisperers, I will eventually like to add 4 or 5.  

This is my config.   I have followed advice to clear my cached accessories, but that doesn't help.  My Homebridge gets in a loop if I include both below devices, reports the following error and then restarts.  

`
        {
            "name": "Veg Beds",
            "sensorSerial": "98f4abcb9e43",
            "pullInterval": 60,
            "debug": false,
            "accessory": "netro-whisperer"
        },
        {
            "name": "Main Border",
            "sensorSerial": "98cdac4896c4",
            "debug": true,
            "accessory": "netro-whisperer"
        }
`

```
[3/6/2023, 8:21:34 AM] Error: Cannot add a Characteristic with the same UUID as another Characteristic in this Service: E863F10F-079E-48FF-8F27-9C2605A29F52
    at NetroSensor.EveService.WeatherService.Service.addCharacteristic (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Service.ts:589:15)
    at NetroSensor.EveService.WeatherService.Service.getCharacteristic (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Service.ts:691:29)
    at NetroSensor.EveService.WeatherService.Service.setCharacteristic (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Service.ts:758:10)
    at /usr/local/lib/node_modules/homebridge-netro-whisperer/index.js:245:48
    at Request._callback (/usr/local/lib/node_modules/homebridge-netro-whisperer/node_modules/homebridge-http-base/src/http.ts:95:13)
    at Request.self.callback (/usr/local/lib/node_modules/homebridge-netro-whisperer/node_modules/request/request.js:185:22)
    at Request.emit (node:events:513:28)
    at Request.<anonymous> (/usr/local/lib/node_modules/homebridge-netro-whisperer/node_modules/request/request.js:1154:10)
    at Request.emit (node:events:513:28)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-netro-whisperer/node_modules/request/request.js:1076:12)
```

Any ideas? 

Thanks. 
Simon

**Comment by ChristophePretty** [comment]
Hi,

Unfortunately I have to "simulate" a "Eve weather station" and I did not figure how to have 2 weather stations at the same time in the same homebridge.
BUT, the good news, is that homebridge allows you to run an accessorie in its own homebridge instance, so you can add as many whisperer as you want. The only drawbacks is that you need to add manually all the homebridge instance to your home app.
Here is the config settings to do it:
``` 
{
            "accessory": "netro-whisperer",
            "name": "Jardin",
            "sensorSerial": "1234567890",
            "pullInterval": 15
        },
        {
            "accessory": "netro-whisperer",
            "_bridge": {
                "username": "11:22:33:44:55:66",
                "port": 12345
            },
            "name": "Balcon",
            "sensorSerial": "2345678901",
            "pullInterval": 15
        },
```

In that example, I have "Jardin" in my default homebridge and "Balcon" in a second homebridge instance.
For the username and port, you can use anything you want as soon as it is not already used. 
See more info on **child bridge** on the official wiki: https://github.com/homebridge/homebridge/wiki/Child-Bridges

**Comment by simons-plugins** [comment]
Thank you.  Even better I have just managed to replace the battery on 2 dead Whisperers so I have 2 more to add.  
Manual config is fine to do.

**Comment by ChristophePretty** [comment]
Cool!

If you are using the "config-ui" plugin (https://github.com/oznu/homebridge-config-ui-x)
There is some UI to help you editing the config file, but manually is not that complex...

**Comment by ChristopheG666** [comment]
See https://github.com/ChristopheG666/homebridge-netro-whisperer/issues/1#issuecomment-1455799475 on how to configure several whisperer

**Comment by ChristopheG666** [comment]
See https://github.com/ChristopheG666/homebridge-netro-whisperer/issues/1#issuecomment-1455799475
